

--FILTROS SIMPLES--

SELECT * FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO =  '290478'

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Laranja';

SELECT * FROM TABELA_DE_PRODUTOS WHERE EMBALAGEM = 'Lata';

--FILTROS QUANTITATIVOS--

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE > 20;

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE <= 20;

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE <> 18;

SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO < =  '1995-11-14'

--EXPRESSÕES LÓGICAS--

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'MANGA' AND TAMANHO = '470 ml';

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'MANGA' OR TAMANHO = '470 ml';

SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT (SABOR = 'MANGA' AND TAMANHO = '470 ml');

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN ('MANGA', 'LARANJA', 'MELANCIA') AND TAMANHO = '1 litro';

SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN ('Rio de janeiro', 'Sao paulo')

SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN ('Rio de janeiro', 'Sao paulo') AND IDADE >= 20;

SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN ('Rio de janeiro', 'Sao paulo') AND IDADE BETWEEN 20 AND 25;

--USO DO LIKE--

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%limao' --sabores que terminam com a palavra 'limao'

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE 'limao%' --sabores que começam com a palavra 'limao'

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%limao%' --sabores que tem a palavra 'limao'