
--COMANDO DISTINCT

SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS --Selecionando valores unicos

SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS WHERE SABOR = 'maca' --Selecionando valores unicos com sabor maça

SELECT DISTINCT EMBALAGEM, SABOR FROM TABELA_DE_PRODUTOS --Selecionando valores unicos de dois campos

--COMANDO TOP

SELECT TOP 5 * FROM TABELA_DE_PRODUTOS --selecionando os 5 primeiros registros

--ORDER BY

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA ASC;  -- preço do menor para o maior

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA desc;  -- preço do maior para o menor

--COMANDO GROUP BY

SELECT CIDADE, SUM(IDADE) FROM TABELA_DE_CLIENTES GROUP BY CIDADE --Somando as idades das cidades

SELECT CIDADE, SUM(LIMITE_DE_CREDITO) AS TOTAL_DE_CREDITO FROM TABELA_DE_CLIENTES GROUP BY CIDADE --Somando o limite de credito das cidades

SELECT CIDADE, AVG(LIMITE_DE_CREDITO) AS MEDIA_CREDITO FROM TABELA_DE_CLIENTES GROUP BY CIDADE --media do limite de credito das cidades

SELECT CIDADE, COUNT(*) AS NUMERO_DE_CLIENTES FROM TABELA_DE_CLIENTES GROUP BY CIDADE --TOTAL DE CLIENTES DE CADA CIDADE

SELECT EMBALAGEM, COUNT(*) AS NUMERO_DE_PRODUTOS_POR_EMBALAGEM FROM TABELA_DE_PRODUTOS WHERE SABOR = 'LARANJA' GROUP BY EMBALAGEM --NUMERO DE PRODUTOS POR EMBALAGEM

--COMADO HAVING (FUN~ÇÃO DE AGREGAÇÃO COM CONDIÇÃO

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS CREDITO FROM TABELA_DE_CLIENTES GROUP BY ESTADO HAVING SUM(LIMITE_DE_CREDITO) > 90000

--ESTRUTURA DE CLASSIFICAÇÃO

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
	(CASE WHEN PRECO_DE_LISTA > 12 THEN 'PRODUTO CARO'
		  WHEN PRECO_DE_LISTA >7 AND PRECO_DE_LISTA <12 THEN 'PRODUTO EM CONTA'
		  ELSE 'PRODUTO BARATO' END) AS CLASSIFICACAO
FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga';

