

select * from TABELA_DE_VENDEDORES;


-- INNER JOIN (SELECIONA UM CAMPO EM COMUM ENTRE AS DUAS TABELAS)

select NOTAS_FISCAIS.MATRICULA, TABELA_DE_VENDEDORES.NOME, count(*) as NUMERO_NOTAS 
-- Seleciona as colunas MATRICULA de NOTAS_FISCAIS, NOME de TABELA_DE_VENDEDORES e conta o número de registros agrupados (alias: NUMERO_NOTAS)
from NOTAS_FISCAIS
-- Especifica a tabela NOTAS_FISCAIS como a tabela principal da consulta
inner join TABELA_DE_VENDEDORES
-- Realiza uma junção interna (inner join) com a tabela TABELA_DE_VENDEDORES
on NOTAS_FISCAIS.MATRICULA = TABELA_DE_VENDEDORES.MATRICULA
-- Define a condição de junção onde a coluna MATRICULA em NOTAS_FISCAIS deve ser igual à coluna MATRICULA em TABELA_DE_VENDEDORES
group by NOTAS_FISCAIS.MATRICULA, TABELA_DE_VENDEDORES.NOME;
-- Agrupa os resultados pelas colunas MATRICULA de NOTAS_FISCAIS e NOME de TABELA_DE_VENDEDORES

-- RIGHT JOIN (SOMENTE OS CAMPOS EM COMUM DA TABELA DA ESQUERDA E TODO MUNDO DA TABELA DA DIREITA




-- LEFT JOIN (SOMENTE OS CAMPOS EM COMUM DA TABELA DA DIREITA E TODO MUNDO DA TABELA DA ESQUERDA
SELECT DISTINCT 
TC.CPF AS CPF_DO_CADASTRO, TC.NOME AS NOME_DO_CLIENTE, NF.CPF AS CPF_DA_NOTA
FROM TABELA_DE_CLIENTES TC 
INNER JOIN NOTAS FISCAIS NF ON TC.CPF = NF.CPF;


-- FULL JOIN (PEGA TODO MUNDO DAS DUAS TABELAS)